# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'mobile_architecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile_architecture

  target 'mobile_architectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobile_architectureUITests' do
    # Pods for testing
  end

end
